apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ibm-entitled-registry-credentials
  namespace: ci
spec:
  encryptedData:
    IBM_ENTITLED_REGISTRY_PASSWORD: AgAUz+TCFnwPEPZnCCzmU0uQ+YKMZ9Wk3DrYHOs9DmzJFxBIBOi3DRXBqL1BGvjRg82dr5VC+BfX7A6FLUidbhhpWnMus07vhcXhLV+o2fMyOshtyL+Pted/n/JPWJDigscgpZOcAUN+p7mgX7LGSdW4KShbxjjowW65/Ia5aPNaZ5SWLrs7VdjNdH7oRwLJxVivWMhsRBPFazqNajoSUauOMqabG+q7XsovyaBbb9vMqv53zfZ4AZf3ASMwEekGR4Yfd2nTWJNzlHRx1k2ssjVFdiYrWnK0TVacL4Xq7sphUQy0HgZEGKLG5hH2cyi/AhKuWqvfpoTQVqkxMtnKFbOiQt2Ay708Jr1ENcDsoW4DDcE5nUaBNV2etrzAXxnwuTaC9Yx8UXfl2Vmws268Cw0BuCtTbddP1eh45GeNkqp3Qkhp0a129AtrJLsbCBnTpSmZ3QIC3gx+LR/u9DUwmxRHZ8z9KWZcv9QgAyFIDZ5I5BrfPvVOm1t39HFqf3puSmqci14vytRch9DvAXEmLsIcTvV/EZA+mRX2ywmYTjKsLSQry1D1Z8dRA2QfnB0hwFAvIxRVCauhS/7r7vcN/WIQLjjKFbDmmzfjEzVrAvetHAxj0mp1BwwXspE8Kuw3oGtsd2Ab36GOluyEljqO2dpmY3l3jB4nSQEgqR2JcuIpXttwpJrLXp/f2jL+w2Eoy9JngZaFaSM53x8GY6D6kH5bl3FS949YZkNn7YEmaJIlN4xZVHkg4yYxQyBMcFLzncTzvlkI4vW5QukZiCDVPF2PGv2qTBCimvHV5cnfFvspC1yTkQP2REuZxKwGYJ+0BKbv+VWlvMrsQHGN4A/fsgxfE73l0tknnhaDO4Okyjv0VlJ1Vg8B2x5ZsYhSYEdyIvU5OQVa8eJ+uXyJ6sKYypzz+U3yCDINzdBejIpXv7jA3uvJ/zg0LfXcl3zw7sKhjqc=
    IBM_ENTITLED_REGISTRY_USER: AgCXUCutfxYwQUceafiFQY9KNileXGygSNYt1XFQvCjIGMIHrY2RGdJquFE2m7PmsRZR2y5rFKjASqDYUAmwFGRdYZCFqSWzI3SMJWbEjEWhWhutPB+5jchPHpQlPhPRHUT+YJUPMcVMWTQ9WIO+QsQgO8YsedQicfe0ObRvhxex6FGwWzl92ETvLpAeWGGMPKnS1x5OfvfblBycJAlg4iVE4jKirAz2hOlzx1+Pssbd9T5CMN/5ZWEs61IHsBy6WzbJTak6fdjEcPtXjmWSKenUQsg6sF/pnVuL2rtsC3LuCbYjQbBk6raW83kgZQlvys6Zl7wwSmTYp/rLJ9y0iWQooQCAXECl0mezeJONvZijjgFpQDB3QOVVOXiB1hs90MljHbo9fpUFwIffAkMH1i0a2KVH0Hu5UWi6+xlTjiquK04Pz2e4+ZFLuTRUzo0B3CFHYeJIYmAdrV4dWbNgUFKULr0NTRVoKl/r0tL8gwhn262tnGJg/F0iFnwBcCQ9KNxiWt+mmteUWBaeWwr8zP+C32260xul0JsrzkSamKlv9iErwfptJxZy9if7GCAltU96XhwqPVNk63RVfRXHPVel6x235Tr4qy/nZ0u9Fyo3qk1m0Tb8Zw9ug8PEENu47Hye7sVLQXZ+oBdEOHjONwZO6x7tWqSXYOLlUs6KI1JE+9IzBLlldD7ZptOiZfSvAg9L/A==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: ibm-entitled-registry-credentials
      namespace: ci

